config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount ActionCable.server => "/cable"

  scope '(:locale)', locale: /fr|en/ do

    root to: 'game_sessions#new'
    get 'creator/show'
    resources :game_sessions_quick, only: [:new], shallow: true do
      resources :rounds_quick, only: [:show, :update, :index]
    end

    resource :rules, only: [:show]
    resources :users, only: [:edit, :update, :show]
    resource :path, only: [:show]

    resources :game_sessions, only: [:new, :create, :show], shallow: true do
      resources :messages, only: [:create]
      resources :rounds, only: [:index, :new, :create, :show, :update], shallow: true do
        resources :round_participations, only: [:new, :create, :index] do
          resources :visited_pages, only: [:create, :index]
        end
      end
    end

  end

end

app/controllers/rounds_quick_controller.rb
require 'json'
require 'open-uri'

class RoundsQuickController < ApplicationController
  skip_before_action :authenticate_user!
  skip_before_action :verify_authenticity_token

  def new
    @round = Round.new
    @game_session = GameSession.find(params[:game_session_id])
    @wiki_pages = WikiPage.all.sort_by { |wiki_page| wiki_page.title }
  end

  def show
    @round = Round.find(params[:id])
    @game_session = @round.game_session
    @round.game_mode = params[:game_mode]
    @round.game_options = params[:round][:game_options]
    @round.search_bar = params[:round][:search_bar]
    @round.reverse = params[:round][:reverse]
    @round.back = params[:round][:back]
    @round.charlie = params[:round][:charlie]

    if params[:round][:start_page] == ""
      @round.start_page_url = random_page_url
      @round.start_page = random_page_title(@round.start_page_url)
      @round.start_page_random = true
    else
      @round.start_page = WikiPage.find(params[:round][:start_page]).title
      @round.start_page_url = WikiPage.find(params[:round][:start_page]).url
    end

    if params[:round][:end_page] == ""
      @round.end_page_url = random_page_url
      @round.end_page = random_page_title(@round.end_page_url)
      @round.end_page_random = true
    else
      @round.end_page = WikiPage.find(params[:round][:end_page]).title
      @round.end_page_url = WikiPage.find(params[:round][:end_page]).url
    end

    t = Time.now
    start_time = t.to_f * 1000
    @round.update(start_time: start_time)
    if @round.save
      round_participation = RoundParticipation.new
      if locale == :en
        @unknown_user = User.find_by(username: "ModeSoloEN")
      else
        @unknown_user = User.find_by(username: "ModeSoloFR")
      end
      round_participation.user = @unknown_user
      round_participation.round = @round
      if round_participation.save
        @host_name = request.protocol + request.host_with_port #pour gérer le soucis de redirection des bouttons
        @round = Round.find(params[:id])
        @game_session = @round.game_session
        @round_participation_id = @round.round_participations.where(user: @unknown_user).first.id
        @round.update(state: "playing")
      else
        render "game_sessions_quick/new"
      end
    else
      render "game_sessions_quick/new"
    end
  end

  def index
    if locale == :en
      @unknown_user = User.find_by(username: "ModeSoloEN")
    else
      @unknown_user = User.find_by(username: "ModeSoloFR")
    end
    @round_participation = RoundParticipation.where(user: @unknown_user).last
    if @round_participation.is_the_best?(locale)
      @round_participation.save_record(@unknown_user, locale)
    end
  end

  def update
    round = Round.find(params[:id])
    round.update(state: 'ended')
    winner = User.find(params[:winner]).username
    ActionCable.server.broadcast("game_session_channel_#{round.game_session.id}", end_game: winner)
    RoundScoreComputer.new(round).call
  end

  private

  def round_params
    params.require(:round).permit(:game_mode, :start_page, :end_page)
  end

  def random_page_url
    if locale == :en
      url_for_random_title = 'https://en.wikipedia.org/api/rest_v1/page/random/title'
    else
      url_for_random_title = 'https://fr.wikipedia.org/api/rest_v1/page/random/title'
    end
  end

  def random_page_title(url)
    page_raw = open(url).read
    page_json = JSON.parse(page_raw)
    page = page_json["items"][0]['title']
  end
end

app/views/rounds_quick/index.html.erb
<div class="main-container">
  <div class="title-container centered-vertically "><h1><span id="score-page-winner"><%= t('.congratulations') %></span></h1></div>
  <div class="content-container centered-vertically">

    <div class="white-container centered-vertically" id="score-page-record-container">
      <% if @round_participation.is_the_best?(locale) %>
        <i class="fas fa-trophy trophy"></i>
        <h4><%= t('.beat_record') %> <strong class="trophy"><%= @round_participation.visited_pages.count - 1 %></strong> clicks</h4>
      <% else %>
        <h4><%= t('.no_record') %></h4>
        <i class="fas fa-heart-broken trophy"></i>
      <% end %>
    </div>

    <div class="cards">
       <% @round_participation.visited_pages.each do |visited_page| %>
        <div class="card centered-vertically path-card">
          <%= visited_page.title %>
        </div>
        <div>
          <i class="fas fa-arrow-down"></i>
        </div>
      <% end %>
        <div class="card centered-vertically path-card">
          <%= t('.victory') %>
        </div>
    </div>



    <div class="white-container centered-vertically" id="score-page-buttons-container">
      <%= link_to t('.end_game'), root_path, class: "btn-tim", id: "go-to-round-index" %>
    </div>
  </div>
</div>

app/views/rounds_quick/show.html.erb
<div class="container-fluid d-flex align-items-center justify-content-center">
    <div id="game-container" class="" >

      <h1 id="wikipage-title-container"></h1>
      <div id="wikipage-container">
      </div>

      <div id="quit-icon-container">
        <%= link_to "#{@host_name}#{root_path}", class: "quit-btn" do %>
          <i class="far fa-times-circle" id="quit-icon"></i>
        <% end %>
      </div>


      <div id="path-icon-container">
        <i class="fas fa-route" id="path-icon"></i>
      </div>

      <% if @round.search_bar %>
        <div id="game-actions-search">
          <div id="search-icon-container">
            <i class="fas fa-search" id="search-icon"></i>
          </div>
          <input id="seach-field" type="text" value=""></>
        </div>
      <% end %>


      <div id="game-actions-bar">
        <% if @round.back %>
          <i class="fas fa-chevron-circle-left" id="action-previous-page"></i>
        <% else %>
          <div> </div>
        <% end %>
        <div id="timer-container">00:00:00</div>

        <i class="fas fa-bullseye" id="action-target-page"></i>
      </div>
    </div>
</div>

<div id="info-your-target-modal" class="modal">
  <div id="info-your-target-modal-content" class="modal-content">
    <div id="info-your-target-modal-header">
      <span class="close" id="info-close">&times;</span>
    </div>
    <div id="info-your-target-modal-container">
      <div id="info-game-counter"><%= t('.stating_in') %> </div>
      <div id="info-game-mode"><%= t('.game_mode_is') %> <%= @round.game_mode %></div>
      <h1 id="info-game-end-page-title-container"></h1>
      <div id="info-game-end-page-container"></div>
      <div id="info-game-counter-big"></div>
    </div>
  </div>
</div>

<div id="game-path-modal" class="modal">
  <div class="modal-content justified">
    <span class="close" id="close-game-path-modal">&times;</span>
    <h1><%= t('.current_path') %></h1>
    <div id="beginning-of-the-path" class="centered-vertically"></div>
  </div>
</div>

<div id="game-end-modal" class="modal">
  <div class="modal-content centered-vertically">
    <h1><%= t('.round_ended') %></h1>
    <h2 id="game-end-modal-winner"><%= t('.winner_is') %> </h2>
    <%= link_to t('.results'), "#{@host_name}#{game_sessions_quick_rounds_quick_index_path(@game_session)}", class: "btn-tim", id:"to-results-btn" %>
  </div>
</div>

<audio id="malus-reverse" preload="true">
 <source src='/reverse.wav' type="audio/wav">
</audio>

<audio id="link-clicked" preload="true">
 <source src='/link_click.mp3' type="audio/mpeg">
</audio>

<audio id="victory-song" preload="true">
 <source src='/victory.mp3' type="audio/mpeg">
</audio>

<audio id="loosing-song" preload="true">
 <source src='/loosing.mp3' type="audio/mpeg">
</audio>

<div id="game-info"
  data-current-user="<%= @unknown_user.id %>"
  data-round="<%= @round.id %>"
  data-state= "init"
  data-winner= ""
  data-options= "<%= @round.game_options %>"
  data-start-page="<%= @round.start_page %>"
  data-end-page="<%= @round.end_page %>"
  data-current-page="<%= @round.start_page %>"
  data-participation = "<%= @round_participation_id  %>"
  data-game-mode = "<%= @round.game_mode %>"
  data-start-time = "<%= @round.start_time %>"
  data-malus-sender = ""
  data-malus = "none"
  data-reverse = "<%= @round.reverse %>"
  data-charlie = "<%= @round.charlie %>"
  data-language = "<%= locale %>">
</div>

<% content_for :after_js do %>
  <script>
    App['game_session_channel_<%= @game_session.id %>'] = App.cable.subscriptions.create(
    { channel: 'GameSessionChannel', game_session_id: <%= @game_session.id %> },
    {received: (data) => {
      console.log(data);
      const gameInfo = document.getElementById('game-info');
      const gameEndModalWinner = document.getElementById('game-end-modal-winner');

      if(data['end_game']){
        gameInfo.dataset.winner = data['end_game'];
        gameEndModalWinner.innerText= `Winner is : ${gameInfo.dataset.winner}`
        gameInfo.dataset.state = "ended";
      }
    }
    })
  </script>
<% end %>