config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount ActionCable.server => "/cable"

  scope '(:locale)', locale: /fr|en/ do

    root to: 'game_sessions#new'
    get 'creator/show'
    resources :game_sessions_quick, only: [:new], shallow: true do
      resources :rounds_quick, only: [:show, :update, :index]
    end

    resource :rules, only: [:show]
    resources :users, only: [:edit, :update, :show]
    resource :path, only: [:show]

    resources :game_sessions, only: [:new, :create, :show], shallow: true do
      resources :messages, only: [:create]
      resources :rounds, only: [:index, :new, :create, :show, :update], shallow: true do
        resources :round_participations, only: [:new, :create, :index] do
          resources :visited_pages, only: [:create, :index]
        end
      end
    end

  end

end

app/models/game_session.rb
class GameSession < ApplicationRecord
  belongs_to :user
  has_many :rounds
  has_many :round_participations, through: :rounds
  has_many :users, through: :round_participations
  has_many :messages, dependent: :destroy
  validates :user, presence: true
end

app/controllers/game_sessions_controller.rb
class GameSessionsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:new, :create]

  def new
    @game_session = GameSession.new
    @round = Round.new
    @round_participation = RoundParticipation.new
  end

  def create
    @game_session = GameSession.new(user_id: current_user.id, language: locale)
    if @game_session.save
      redirect_to new_game_session_round_path(@game_session)
    else
      render :new
    end
  end

  def show
    # This is the waiting page
    @game_session = GameSession.find(params[:id])
    @messages = Message.where(game_session_id: @game_session.id)
    @round = Round.where(game_session_id: @game_session).last
    ActionCable.server.broadcast("game_session_channel_#{@game_session.id}", player: current_user.username, connected: "Participants : #{@round.round_participations.count}" , new_round_link: helpers.link_to('Nouveau Round', round_round_participations_path(@round), method: :post, class: "btn-tim main-red"))
  end
end

app/views/game_sessions/_messages.html.erb
<div class="message <%= message.from?(current_user) ? "right" : "" %>">
  <p class="message-user-name">- <%= message.user.username %> -</p>
  <div class="message-content"><%= message.content %></div>
</div>

app/views/game_sessions/_player.html.erb
<div class="player">
  <% counter += 1 %>
  <p><%= counter %> : <%= User.find(round_participation.user_id).username %></p>
</div>

app/views/game_sessions/create.html.erb
<h1>GameSessions#create</h1>
<p>Find me in app/views/game_sessions/create.html.erb</p>

app/views/game_sessions/new.html.erb
<div class="main-container">
  <div class="title-container centered-vertically "><h1><span id="#home-page-title">WikiRace</span></h1></div>
  <div class="content-container centered-vertically">
    <div class="white-container centered-vertically">
      <% if user_signed_in? %>

          <%= simple_form_for @game_session, html: { id: 'home-page-options' } do |f| %>
              <%= f.submit t('.create_game'), class: "btn-tim", id: "red-pill" %>
          <% end %>

          <%= text_field_tag "name", "", placeholder: t('.enter_code'), id: "round-input" %>
          <div class="info-bubble-join" id="info-bubble-join">
            <i class="fas fa-info-circle"></i>
          </div>
          <%= button_tag t('.join'),class: "btn-tim", id: "blue-pill" %>


      <% else %>
        <%= link_to t('.play'), new_user_session_path, class: "btn-tim", id:"welcome-btn" %>
        <%= link_to t('.quick_play'), new_game_sessions_quick_path, class: "btn-tim", id:"welcome-btn" %>
      <% end %>
    </div>
  </div>
</div>

<div class="not-visible" id="locale"><%= "#{locale}" %></div>

<div class="modal-info-join">
  <div id="modal-info-join">
    <span><%= t('.code_to_join') %><a href="#close" id="close-join">&#215;</a></span>
    <p><%= t('.join_info') %></p>
    <p><em><strong><%= t('.note') %></strong> <%= t('.join_info_note') %></em></p>
  </div>
</div>

app/views/game_sessions/show.html.erb
<div class="main-container" id="gs-show-main-container">
  <div class="title-container centered-vertically"><h1><%= t('.campfire') %></h1></div>
  <div class="content-container centered-vertically">
    <div class="white-container centered-vertically">
      <%= button_tag t('.invite_friends'),type: 'button', class: "btn-tim", id:"invite-friends-btn" %>
      <%if current_user.id == @game_session.user_id  %>
        <%= simple_form_for @round do |f| %>
          <%= hidden_field_tag :start_game, true %>
          <%= f.button :submit, t('.start_game'), class: "btn-tim", id: "btn-start-game" %>
        <% end %>
      <% else %>
        <%= button_tag "Round Info",type: 'button', class: "btn-tim", id:"round-info-btn" %>
      <%end  %>
      <p id="nbr-player-connected"><%= t('.participants', count: @round.round_participations.count) %></p>
    </div>

    <div id="create-message" class="white-container">
      <div id="message-input">
        <%= simple_form_for [@game_session, Message.new], remote: true do |f| %>
          <%= f.input :content, label: false, placeholder: t('.placeholder') %>
        <% end %>
      </div>

      <div class="messages">
        <% @game_session.messages.each do |message| %>
          <%= render "messages", message: message %>
        <% end %>
        <% @round.round_participations.each do |round_participation| %>
        <p class="new-connection">- <%= User.find(round_participation.user_id).username %> <%= t('.has_joined') %></p>
        <% end %>
      </div>
    </div>
  </div>

  <div id="invite-friends-modal" class="modal">
    <div id="invite-friends-modal-content" class="modal-content">
      <div id="invite-friends-modal-header">
        <span class="close" id="close-invite-friends">&times;</span>
      </div>
      <div class="centered-vertically" id="invite-friends-modal-content-after-header">
        <h4 class="parcours-title" style="margin-bottom: 10px;"><%= t('.invite') %></h4>
        <p><%= t('.code') %><strong id="round-id-link"><%= @round.id %></strong></p>
        <p><i class="fas fa-sort invit-arrow"></i></p>
        <p><%= t('.QRcode') %></p>
        <br>
        <img style="max-width: 150px;" src=<%= "http://api.qrserver.com/v1/create-qr-code/?data=http://www.wikirace.xyz/rounds/#{@round.id}/round_participations/new/&size=[150]x[150]" %> alt="Le QR Code pour rejoindre la partie" title="QR Code" />
        <br>
        <p><i class="fas fa-sort  invit-arrow"></i></p>
        <p><%= t('.link') %></p>
        <button id="copy-button" class="btn-tim main-red"><%= t('.copy_link') %></button>
        <input id="url" style="opacity: 0;" type="text" value="http://www.wikirace.xyz/rounds/<%= @round.id %>/round_participations/new" readonly></input>
      </div>
    </div>
  </div>

  <div id="round-info-modal" class="modal">
    <div id="round-info-modal-content" class="modal-content">
      <div id="round-info-modal-header">
        <span class="close" id="close-round-info">&times;</span>
      </div>
      <div class="centered-vertically" id="round-info-modal-content-after-header">
        <h3><%= t('.game_details') %></h3>

        <div class="info-option-container">
          <% if  @round.start_page_random == false %>
             <h4 class="text-center"><i class="fas fa-play-circle"></i> <%= t('.starting_page') %></h4><p><%= @round.start_page %></p>
          <% else %>
            <h4 class="text-center"><i class="fas fa-play-circle"></i> <%= t('.starting_page') %></h4><p><%= t('.random_page') %></p>
          <% end %>
        </div>
        <div class="info-option-container">
          <% if  @round.end_page_random == false %>
            <h4 class="text-center"><i class="fas fa-bullseye"></i> <%= t('.target_page') %></h4><p class="mb-0"><%= @round.end_page %></p>
          <% else%>
            <h4 class="text-center"><i class="fas fa-bullseye"></i> <%= t('.target_page') %></h4><p class="mb-0"><%= t('.random_page') %></p>
          <% end %>
        </div>

        <div class="info-option-container">
          <h4 class="text-center"><%= t('.game_mode') %><br></h4><p><%= @round.game_mode %></p>
          <p class="text-center"><i><%= t('.game_mode_description') %></i></p>
        </div>

        <% if @round.game_options != nil %>
          <div class="info-option-container">
            <h4 class="text-center"><%= t('.game_options') %><br></h4>
            <p><%= t('.search_bar') %><%= @round.search_bar ? t('.is_on') : t('.is_off') %></p>
            <p><%= t('.reverse') %><%= @round.reverse ? t('.is_on') : t('.is_off') %></p>
            <p><%= t('.back') %><%= @round.back ? t('.is_on') : t('.is_off') %></p>
          </div>
        <% end %>
        <%= button_tag "OK",type: 'button', class: "btn-tim", id:"ok-btn" %>
      </div>
    </div>
  </div>
</div>

<audio id="message-received" preload="true">
 <source src='/new_message.mp3' type="audio/mpeg">
</audio>

<audio id="player-joined" preload="true">
 <source src='/player_joining.mp3' type="audio/mpeg">
</audio>

<audio id="link-copied" preload="true">
 <source src='/link_click.mp3' type="audio/mpeg">
</audio>

<% content_for :after_js do %>
  <script>
    const messageReceived = document.getElementById('message-received');
    messageReceived.play;

    App['game_session_channel_<%= @game_session.id %>'] = App.cable.subscriptions.create(
    { channel: 'GameSessionChannel', game_session_id: <%= @game_session.id %> },
    {received: (data) => {
        if (data.message_partial === undefined && data.player === undefined && data.end_game === undefined) {
          window.location = '<%= round_path(@round) %>';

        } else if (data.content === undefined && data.player === undefined && data.end_game === undefined) {
          const messagesContainer = document.querySelector('.messages');
          messagesContainer.insertAdjacentHTML('afterbegin', data.message_partial);
          if (data.current_user_id == <%= current_user.id %>) {
            const  input = document.querySelector('#message_content');
            input.value = '';
          }
          const messageReceived = document.getElementById('message-received');
          const messageReceivedPromise = messageReceived.play();
          messageReceived.currentTime = 0;
          if (messageReceivedPromise !== undefined) {
            messageReceivedPromise.then(function() {
              messageReceived.play();
            }).catch(function(error) {
              messageReceived.play();
              console.log("Probleme de chargement du son pour message recu!");
            });
          }
        } else if (data.content === undefined && data.message_partial === undefined && data.end_game === undefined) {
          const playerConnected = document.querySelector('.messages');
          playerConnected.insertAdjacentHTML('afterbegin', `<p class="new-connection">- ${data.player} <%= t('.has_joined') %></p>`);
          const numberOfPlayers = document.getElementById('nbr-player-connected');
          numberOfPlayers.innerText = data.connected
          const playerJoinSong = document.getElementById('player-joined');
          const playerJoinSongPromise = playerJoinSong.play();
          playerJoinSong.currentTime = 0;
          if (playerJoinSongPromise !== undefined) {
            playerJoinSongPromise.then(function() {
              playerJoinSong.play();
            }).catch(function(error) {
              playerJoinSong.play();
              console.log("Probleme de chargement du son pour player joined!");
            });
          }
        } else if (data.content === undefined && data.message_partial === undefined && data.player === undefined) {
          console.log('modal pop up');

        } else {
          console.log('canard');
        }
      }
    })
  </script>
<% end %>