config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount ActionCable.server => "/cable"

  scope '(:locale)', locale: /fr|en/ do

    root to: 'game_sessions#new'
    get 'creator/show'
    resources :game_sessions_quick, only: [:new], shallow: true do
      resources :rounds_quick, only: [:show, :update, :index]
    end

    resource :rules, only: [:show]
    resources :users, only: [:edit, :update, :show]
    resource :path, only: [:show]

    resources :game_sessions, only: [:new, :create, :show], shallow: true do
      resources :messages, only: [:create]
      resources :rounds, only: [:index, :new, :create, :show, :update], shallow: true do
        resources :round_participations, only: [:new, :create, :index] do
          resources :visited_pages, only: [:create, :index]
        end
      end
    end

  end

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close" style="padding: 0rem 1.25rem;">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close" style="padding: 0rem 1.25rem;">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" id="main-navbar">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%#= image_tag "wikirace-logo2.png", class: "logo-hover" %>
    <div id="logo"></div>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li><%= link_to t('english'), root_path(locale: :en), class: "nav-item active nav-link" %></li>
      <li><%= link_to t('french'), root_path(locale: :fr), class: "nav-item active nav-link" %></li>
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to t('home'), root_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <% if current_user.photo.attached? %>
            <%= image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= cl_image_tag "wikipadia_ytkglo.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to t('stats'), user_path(current_user[:id]), class: "dropdown-item" %>
            <%= link_to t('game_rules'), rules_path, class: "dropdown-item" %>
            <%= link_to t('edit_user'), edit_user_path(current_user[:id]), class: "dropdown-item" %>
            <%= link_to t('change_email_pw'), edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to t('about'), creator_show_path, class: "dropdown-item" %>
            <%= link_to t('sign_out'), destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
            <%= link_to t('game_rules'), rules_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to t('log_in'), new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>

</div>