config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount ActionCable.server => "/cable"

  scope '(:locale)', locale: /fr|en/ do

    root to: 'game_sessions#new'
    get 'creator/show'
    resources :game_sessions_quick, only: [:new], shallow: true do
      resources :rounds_quick, only: [:show, :update, :index]
    end

    resource :rules, only: [:show]
    resources :users, only: [:edit, :update, :show]
    resource :path, only: [:show]

    resources :game_sessions, only: [:new, :create, :show], shallow: true do
      resources :messages, only: [:create]
      resources :rounds, only: [:index, :new, :create, :show, :update], shallow: true do
        resources :round_participations, only: [:new, :create, :index] do
          resources :visited_pages, only: [:create, :index]
        end
      end
    end

  end

end

app/models/round_participation.rb
class RoundParticipation < ApplicationRecord
  belongs_to :user
  belongs_to :round
  has_many :visited_pages
  validates :user, presence: true
  validates :round, presence: true
  validates :user, uniqueness: { scope: :round, message: "There can only be a RP per user per round" }

  def is_the_best?(locale)
    start_page = WikiPage.where(title: self.round.start_page, language: "#{locale}")
    end_page = WikiPage.where(title: self.visited_pages.last.title, language: "#{locale}")
    record_path = Path.find_by(start_page: start_page, end_page: end_page)
    if record_path.blank?
      return true
    else
      if self.visited_pages.count < record_path.points.count
        return true
      elsif record_path.user_id == self.user_id && self.visited_pages.count == record_path.points.count
        return true
      end
      return false
    end
  end

  def save_record(current_user, locale)
    start_page_title = self.round.start_page
    if WikiPage.find_by(title: start_page_title, language: locale).blank?
      WikiPage.create(title: start_page_title, url: self.round.start_page_url, language: locale)
    end
    start_page = WikiPage.find_by(title: start_page_title, language: "#{locale}")

    end_page_title = self.visited_pages.last.title
    if WikiPage.find_by(title: end_page_title, language: locale).blank?
      WikiPage.create(title: end_page_title, url: self.round.end_page_url, language: locale)
    end
    end_page = WikiPage.find_by(title: end_page_title, language: locale)

    record_path = Path.find_by(start_page: start_page, end_page: end_page)

    # creation of the new path
    if start_page == end_page
      #nothing happens
    elsif record_path.blank?
      Path.create(user: current_user, start_page: start_page, end_page: end_page, duration: (self.end_time.to_i - self.round.start_time.to_i))
    else
      record_path.update(user: current_user, start_page: start_page, end_page: end_page, duration: (self.end_time.to_i - self.round.start_time.to_i))
      record_path.points.each {|point| point.destroy}
    end

    # creation of points after the creation of the new WikiPages
    record_path = Path.find_by(start_page: start_page, end_page: end_page)
    position = 0
    self.visited_pages.each {|visited_page|
      if WikiPage.find_by(title: visited_page.title, language: "#{locale}").blank?
        WikiPage.create(title: visited_page.title, url: visited_page.url, language: locale)
      end
      position += 1
      Point.create(position: position, wiki_page: WikiPage.find_by(title: visited_page.title), path: record_path)
    }
  end

  # def rank_for_round
  #   @round = self.round
  #   @round_participations = @round.round_participations
  #   case self.round.game_mode

  #   when "Premier arrivé"
  #     @round_participations.each { |round_participation|
  #       if round_participation.visited_pages.last == round_participation.round.end_page
  #         @rank = 1
  #       else
  #         @round_participations.sort_by{ |round_participation| round_participation.visited_pages.count }
  #         @rank = @round_participations.index(self) + 1
  #       end
  #     }

  #   when "Limite de temps"
  #     @round_participations.each { |round_participation|
  #       if round_participation.visited_pages.last == round_participation.round.end_page
  #         @round_participations.sort_by{ |round_participation| round_participation.visited_pages.last.created_at }
  #         @rank = @round_participations.index(self) + 1
  #       else
  #         @round_participations.sort_by{ |round_participation| round_participation.user.score_for_round }
  #         @rank = @round_participations.index(self) + 1
  #       end
  #     }

  #   when "Limite de clicks"
  #     @round_participations.each { |round_participation|
  #       if round_participation.visited_pages.last == round_participation.round.end_page
  #         @round_participations.sort_by{ |round_participation| round_participation.visited_pages.count }
  #         @rank = @round_participations.index(self) + 1
  #       else
  #         @round_participations.sort_by{ |round_participation| round_participation.user.score_for_round }
  #         @rank = @round_participations.index(self) + 1
  #       end
  #     }

  #   when "Limite de temps & clicks"
  #     @round_participations.each { |round_participation|
  #       if round_participation.visited_pages.last == round_participation.round.end_page
  #         @round_participations.sort_by{ |round_participation| round_participation.visited_pages.count }
  #         #TODO: je n'ai pas fait le 2em niveau de sorting (dans le cas ou l'on a le meme nombre de click mais un temps différent)
  #         @rank = @round_participations.index(self) + 1
  #       else
  #         @round_participations.sort_by{ |round_participation| round_participation.user.score_for_round }
  #         @rank = @round_participations.index(self) + 1
  #       end
  #     }

  #   when "Pas de limites"
  #     @round_participations.each { |round_participation|
  #       if round_participation.visited_pages.last != round_participation.round.end_page
  #         @rank = nil
  #       else
  #         @round_participations.sort_by{ |round_participation| round_participation.user.score_for_round }
  #         @rank = @round_participations.index(self) + 1
  #       end
  #     }

  #   else
  #     raise error
  #   end

  #   return @rank
  # end

  # def score_for_round
  #   case self.round.game_mode

  #   when "Premier arrivé"
  #     if self.rank == 1
  #         @score = 100
  #     else
  #         @score = - self.visited_pages.count
  #     end

  #   when "Limite de temps"
  #     if self.rank == 1
  #       @score = 100
  #     elsif self.rank == 2
  #       @score = 50
  #     elsif self.rank == 3
  #       @score = 25
  #     elsif self.rank == nil
  #       @score = - self.visited_pages.count
  #     else
  #       @score = 10
  #     end

  #   when "Limite de clicks"
  #     if self.rank == 1
  #       @score = 100
  #     elsif self.rank == 2
  #       @score = 50
  #     elsif self.rank == 3
  #       @score = 25
  #     elsif self.rank == nil
  #       @score = - ( self.visited_pages.last.created_at - round_participation.round.start_time ) / 10000
  #     else
  #       @score = 10
  #     end

  #   when "Limite de temps & clicks"
  #     if self.rank == 1
  #       @score = 100
  #     elsif self.rank == 2
  #       @score = 50
  #     elsif self.rank == 3
  #       @score = 25
  #     elsif self.rank == nil
  #       @score = - self.visited_pages.count - ( self.visited_pages.last.created_at - round_participation.round.start_time ) / 10000
  #     else
  #       @score = 10
  #     end

  #   when "Pas de limites"
  #     if self.rank == 1
  #       @score = 100
  #     elsif self.rank == 2
  #       @score = 50
  #     elsif self.rank == 3
  #       @score = 25
  #     elsif self.rank == nil
  #       @score = - self.visited_pages.count - ( self.visited_pages.last.created_at - round_participation.round.start_time ) / 10000
  #     else
  #       @score = 10
  #     end

  #   else
  #     raise error
  #   end

  #   return @score
  # end
end

app/controllers/round_participations_controller.rb
class RoundParticipationsController < ApplicationController
  before_action :find_round_and_game_session, except: [:update, :edit]

  def new
    @round_participation = RoundParticipation.new
    @creator = User.find(@game_session.user_id)
  end

  def create
    @round_participation = current_user.round_participations.new(round_id: @round.id)
    @round_participation.save
    redirect_to game_session_path(@game_session)
  end

  def index
    @round_participation = RoundParticipation.where(user: current_user)[0]
    @round_participations = @round.round_participations
    @round_participation = @round.round_participations.select {|round_participation| round_participation.user == current_user}[0]
    if @round_participation.is_the_best?(locale)
      @round_participation.save_record(current_user, locale)
    end
    @game_session = @round_participation.round.game_session
    @next_round = @game_session.rounds.last
    @sorted_round_participations = @round_participations.sort_by{ |round_participation| round_participation.rank}
    @players = @sorted_round_participations.map { |round_participation| round_participation.user }
  end

  private

  def find_round_and_game_session
    @round = Round.find(params[:round_id])
    @game_session = GameSession.find(@round.game_session_id)
  end
end

app/views/round_participations/edit.html.erb
<h1>RoundParticipations#edit</h1>
<p>Find me in app/views/round_participations/edit.html.erb</p>

app/views/round_participations/index.html.erb
<div class="main-container">
  <div class="title-container centered-vertically "><h1><span id="score-page-winner">Round <%= @game_session.rounds.count %> : <%= @sorted_round_participations.first.user.username %> <%= t('.win') %></span></h1></div>
  <div class="content-container centered-vertically">

    <div class="white-container centered-vertically" id="score-page-record-container">
      <% if @sorted_round_participations.first.is_the_best?(locale) %>
        <i class="fas fa-trophy trophy"></i>
        <h4><%= @sorted_round_participations.first.user.username %> <%= t('.beat_record') %> <strong class="trophy"><%= @sorted_round_participations.first.visited_pages.count - 1 %></strong> clicks</h4>
      <% else %>
        <h4><%= t('.no_record') %></h4>
        <i class="fas fa-heart-broken trophy"></i>
      <% end %>
    </div>



    <div class="cards">
      <% @players.each do |player| %>
        <div class="card" data-player="<%= player.id %>">
          <div class="card-left-side">
            <div class="card-rank-container">
              <div class="card-rank">
                <%= player.round_participations.select{|round_participation| round_participation.round == @round }[0].rank %></div>
              </div>
            <div class="card-username"><%= player.username %></div>
          </div>
          <div class="card-right-side">
            <div class="card-score"><%= player.round_participations.select{|round_participation| round_participation.round == @round }[0].score %> pts</div>
            <div class="card-avatar-container">
              <% if player.photo.attached? %>
                <%= image_tag player.photo, class: "card-avatar" %>
              <% else %>
                <%= cl_image_tag "wikipadia_ytkglo.jpg", class: "card-avatar"%>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>



    <% @players.each do |player| %>
      <div id="path-info-modal-player-<%= player.id %>" class="modal">
        <div class="modal-content">


          <div class="modal-header">
            <span id="path-info-modal-close-player-<%= player.id %>" class="close">&times;</span>
          </div>


          <div class="centered-vertically game-font">


            <h2 class="parcours-title"><%= t('.path') %> <%= player.username %>!</h2>
            <div class="time-and-score">
              <% time_gap = player.round_participations.select{|round_participation| round_participation.round == @round }[0].end_time.to_i - @round.start_time.to_i %>
              <% seconds_elapsed = ((time_gap / 1000) % 60).to_i %>
              <% minutes_elapsed = ((time_gap / 1000) / 60 % 60).to_i %>
              <% hours_elapsed = ((time_gap / 1000) / 60 / 60 % 60).to_i  %>
              <p><%= t('.time') %> <%= hours_elapsed %>h <%= minutes_elapsed %>min <%= seconds_elapsed %>s</p>
              <p><%= t('.clicks') %> <%= player.round_participations.select{|round_participation| round_participation.round == @round }[0].visited_pages.count - 1 %></p>
            </div>


            <div style="display: flex; align-items: center; flex-direction: column;">
              <% counter = 0 %>
              <% player.round_participations.select{|round_participation| round_participation.round == @round }[0].visited_pages.each do |visited_page| %>
                <% counter += 1 %>
                  <p style="margin-bottom: 20px;"><%= counter %> : <%= visited_page.title %></p>
                  <% if @round.end_page != visited_page.title %>
                    <i class="fas fa-chevron-circle-down chevrons"></i>
                  <% end %>
              <% end %>
            </div>

          </div>

        </div>
      </div>
    <% end %>



    <div class="white-container centered-vertically" id="score-page-buttons-container">
      <% if current_user.id == @game_session.user_id %>
        <%= link_to t('.new_round'), new_game_session_round_path(@game_session), class: "btn-tim", id: "launch-new-round" %>
      <% else %>
        <% if @next_round.state == 'imminent' %>
        <% raise %>
          <%= link_to t('.new_round'), new_game_session_round_path(@game_session), class: "btn-tim", id: "launch-new-round" %>
        <% elsif @next_round.state == 'playing' %>
          <button class="player_replay_button btn-tim main-red" style="opacity: 0.5;"><i><%= t('.already_started') %></i></button>
        <% else %>
          <button class="player_replay_button btn-tim main-red" style="opacity: 0.5;"><i><%= t('.waiting_for') %> <%= @game_session.user.username %></i></button>
        <% end %>
      <% end %>
      <%= link_to t('.end_game'), game_session_rounds_path(@game_session), class: "btn-tim", id: "go-to-round-index" %>
    </div>
  </div>
</div>



<% content_for :after_js do %>
  <script>
    App['game_session_channel_<%= @game_session.id %>'] = App.cable.subscriptions.create(
    { channel: 'GameSessionChannel', game_session_id: <%= @game_session.id %> },
    {received: (data) => {
      if (data.new_round_link_off) {
        const replayButtonForPlayer = document.querySelector('.main-red');
        replayButtonForPlayer.outerHTML = data.new_round_link_off;
      } else if (data.new_round_link) {
        const replayButtonForPlayer = document.querySelector('.player_replay_button');
        replayButtonForPlayer.outerHTML = data.new_round_link;
      } else {}
      }
    })
  </script>
<% end %>

app/views/round_participations/new.html.erb
<div class="main-container">
  <div class="title-container centered-vertically "><h1><span><%= @creator.username %> <%= t('.invited_you') %></span></h1></div>
  <div class="content-container centered-vertically">
    <div class="white-container centered-vertically">
      <% if @round.state == nil %>
        <p class="display-messages-no-round"><%= t('.not_existing') %></p>
      <% elsif @round.state == "initiated" %>
        <%= link_to t('.join'), round_round_participations_path, method: :post, class:"btn-tim", id:"btn-join"  %>
      <% elsif @round.state == "playing" %>
        <p class="display-messages-no-round"><%= t('.already_started') %></p>
      <% elsif @round.state == "ended" %>
        <p class="display-messages-no-round"><%= t('.already_played') %></p>
      <% else %>
        <p class="display-messages-no-round"><%= t('.issue') %></p>
      <% end %>
    </div>
  </div>
</div>

<% content_for :after_js do %>
  <script>
    App['game_session_channel_<%= @game_session.id %>'] = App.cable.subscriptions.create(
    { channel: 'GameSessionChannel', game_session_id: <%= @game_session.id %> },
    {received: (data) => {
      if (data.new_round_link_off) {
        const replayButtonForPlayer = document.querySelector('#btn-join');
        replayButtonForPlayer.outerHTML = data.new_round_link_off;
      } else {}
      }
    })
  </script>
<% end %>

app/views/round_participations/update.html.erb
<h1>RoundParticipations#update</h1>
<p>Find me in app/views/round_participations/update.html.erb</p>